#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -pe omp 16
#
source /etc/bashrc

module load gcc 
module load star/2.6.0c

GENOMEDIR=/project/bf528/project_3/reference/rn4_STAR/
SAMPLEDIR=/project/bf528/project_3/samples/
STAR --genomeLoad LoadAndExit --genomeDir $GENOMEDIR

STAR  --runThreadN 16 --genomeDir $GENOMEDIR --readFilesCommand zcat --readFilesIn /project/bf528/project_3/samples/SRR1178004_1.fastq.gz /project/bf528/project_3/samples/SRR1178004_2.fastq.gz --outSAMtype BAM Unsorted --outFileNamePrefix ./star_out/

STAR --genomeLoad Remove --genomeDir $GENOMEDIR

  # genomeDir: Where the genome index is stored (created by prof)
  # readFilesCommand: Need this because fastq files are compressed (.gz)
  # readFilesIn: all of the fastq files, all the read1 then all the read2

#STAR --genomeDir /project/bf528/project_3/reference/rn4_STAR/ --readFilesCommand zcat --readFilesIn /project/bf528/project_3/samples/SRR1178004_1.fastq.gz /project/bf528/project_3/samples/SRR1178004_2.fastq.gz --outSAMtype BAM SortedByCoordinate --outFileNamePrefix ./star_out/
